#! /bin/sh
# /etc/init.d/settingSensorIoTPins

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
## para remover este script -- sudo update-rc.d -f  NameOfYourScript remove
case "$1" in
  start)
    echo "Starting noip"
    # run application you want to start
    /home/debian/Sensor-IOT/SensorIoT/settingPins/pins
    ;;
  stop)
    echo "Stopping noip"
    # kill application you want to stop
    killall pins
    ;;
  *)
    echo "Usage: /etc/init.d/settingSensorIoTPins {start|stop}"
    exit 1
    ;;
esac

exit 0
